### PR TITLE
Add FileProfile to ProfileList & Prof.InstanceList

### LINKED ISSUE #302: Requesting for including an AppData file to store the registration timestamp of new application registration
### **Proposal :**
Requesting for APPData file to store the registration time-stamp of applications. If this proposal is considered , then , we require file-profiles included to the load file and OAS.

### **Reason :**
**Initial Plan :**
As a part of the service v1/register-application , a timer has to be initiated to monitor whether an application is approved within the expected time(integerProfile/WaitTimeToApprove).
If the application is not approved within the specified time limit , deregistration of the unapproved application shall be initiated by RegistryOffice.
Initially , we planned to model it in the following way , 
image

**Cons :**
There is a disadvantage in this approach . When the RegistryOffice docker container goes down or gets restarted , the “WaitTimeToApprove” process will be lost.

### **Alternate Plan :** (also Implemented the following flow to verify the proposal)
To overcome the disadvantage , 
1.	while registering an application , the details of the registration-time-stamp shall be store in an application data file.
image
2.	A cyclic job shall be initiated during the startup of the application. This cyclic job monitors whether an application is approved withing the “WaitTimeToApprove” with the help of the registration-time-stamp.
image

### PR DESCRIPTION
**Pull request by openBackhaul**
OaM paths for managing FileProfile will be added during last steps before publishing

Fixes #302

### CODE REVIEW

**Comment by openBackhaul** [comment]
FileProfile added to ProfileList.
Instance of FileProfile added to ProfileInstanceList.
OaM paths for managing the instance of FileProfile will be added during combining individual specification with AP before publishing.

**Review by PrathibaJee — CHANGES_REQUESTED** [review]
Changes in the profiles and profileInstances.yaml file looks good.
Also , shall we include the following profile to the CONFIG file , 
```
{
  "uuid": "ro-2-0-0-file-p-000",
  "profile-name": "file-profile-1-0:PROFILE_NAME_TYPE_FILE_PROFILE",
  "file-profile-1-0:file-profile-pac": {
    "file-profile-capability": {
      "file-identifier": "LOADfile",
      "file-description": "Application name, release number and registration time stamp"
    },
    "file-profile-configuration": {
      "file-path": "../application-data/application-data.json",
      "user-name": "RegistryOffice",
      "password": "Operations to add password",
      "operation": "file-profile-1-0:OPERATION_TYPE_READ_WRITE"
    }
  }
}
```

Thanks.

**Comment by openBackhaul** [comment]
Sorry, stupid mistake.
Added the ProfileInstance to CONFIGfile.
Result is as proposed.

**Review by PrathibaJee — APPROVED** [review]
Thanks for including the file-Profile to the CONFIGfile.

**Pull request merged**
